name: Merge master to dev

on:
    push:
        branches:
            - master

jobs:
    merge_master_to_dev:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Merge master -> dev
              uses: devmasx/merge-branch@master
              with:
                  type: now
                  head_to_merge: master
                  target_branch: dev
                  github_token: ${{ github.token }}
